import type {
  A2Data,
  A3Data,
  A4Data,
  A5Data,
  InvestigadoData,
  NotificacionData,
  TestigoData,
} from "../types";

export const a2Defaults: A2Data = {
  referencia: "",
  numero: "",
  nombre: "",
  dni: "",
  domicilio: "",
  distrito: "Iquitos",
  provincia: "Maynas",
  departamento: "Loreto",
  celular: "S/N",
  email: "S/C",
  modalidadDelito: "",
  condicion: "Testigo",
  imputados: "",
  agraviado: "El Estado Peruano",
  citacion1: "",
  citacion2: "",
  citacion3: "",
  fechaDiligencia: "",
  horaDiligencia: "",
  fechaDocumento: "",
};

export const a3Defaults: A3Data = {
  referencia: "",
  numero: "",
  nombre: "",
  dni: "",
  domicilio: "",
  distrito: "Iquitos",
  provincia: "Maynas",
  departamento: "Loreto",
  celular: "S/N",
  email: "S/C",
  modalidadDelito: "",
  condicion: "Testigo",
  imputados: "",
  agraviado: "El Estado Peruano",
  citacion1: "",
  citacion2: "",
  citacion3: "",
  fechaDiligencia: "",
  horaDiligencia: "",
  fechaDocumento: "",
};

export const a4Defaults: A4Data = {
  referencia: "",
  numero: "",
  nombre: "",
  dni: "",
  domicilio: "",
  distrito: "Iquitos",
  provincia: "Maynas",
  departamento: "Loreto",
  celular: "S/N",
  email: "S/C",
  fechaDiligencia: "",
  horaDiligencia: "",
  fiscalia: "Fiscalía Provincial Corporativa Especializada en Delitos de Corrupción de Funcionarios de Loreto",
  delito: "",
  agraviado: "El Estado Peruano",
  fechaDocumento: "",
  disposicionFiscal: "",
  folios: "",
};

export const a5Defaults: A5Data = {
  referencia: "",
  numero: "",
  nombre: "",
  dni: "",
  domicilio: "",
  distrito: "Iquitos",
  provincia: "Maynas",
  departamento: "Loreto",
  celular: "S/N",
  email: "S/C",
  fechaDiligencia: "",
  horaDiligencia: "",
  fiscalia: "Fiscalía Provincial Corporativa Especializada en Delitos de Corrupción de Funcionarios de Loreto",
  delito: "",
  agraviado: "El Estado Peruano",
  merito: "",
  fechaDocumento: "",
  disposicionFiscal: "",
  folios: "",
};

export const investigadoDefaults: InvestigadoData = {
  numero: "",
  nombre: "",
  domicilio: "",
  carpetaFiscal: "",
  fechaDiligencia: "",
  hora: "",
  delito: "",
  agraviado: "",
  descripcionHecho: "",
  fechaDocumento: "",
};

export const testigoDefaults: TestigoData = {
  numero: "",
  nombre: "",
  domicilio: "",
  carpetaFiscal: "",
  fechaDiligencia: "",
  hora: "",
  investigados: "",
  delito: "",
  agraviado: "",
  descripcionHecho: "",
  fechaDocumento: "",
};

export const notificacionDefaults: NotificacionData = {
  numero: "",
  nombre: "",
  domicilio: "",
  carpetaFiscal: "",
  delito: "",
  fechaDocumento: "",
  citados: [],
};
